# Generated by Django 3.1.6 on 2021-02-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirasi', '0003_auto_20210225_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspiration',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
