# Generated by Django 3.1.6 on 2021-03-02 01:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aspirasi', '0004_aspiration_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspiration',
            name='aspirasi',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aspiration',
            name='instansi_tujuan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aspiration',
            name='lokasi',
            field=models.CharField(max_length=255),
        ),
    ]
