# Generated by Django 3.1.6 on 2021-03-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspirasi', '0005_auto_20210302_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
