# Generated by Django 3.1.6 on 2021-03-03 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aspirasi', '0006_auto_20210302_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspiration',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
